name: ventures
favicon: null
layout_spectrum: 0.032866894733160734
typography_spectrum: 0.5620146272704005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.08032697439193726
  lightness: 0.3650743083562702
  saturation: 0.17161023220978677
  rhythmicContrast: 0.05460790731012821
purpose: []
